FROM node:20-alpine

# Create a non-root user for security
RUN addgroup app && adduser -S -G app app

USER app

WORKDIR /app

COPY package*.json ./

USER root
RUN corepack enable && corepack prepare pnpm@10.10.0 --activate
RUN chown -R app:app .
USER app

RUN pnpm install

COPY . .

EXPOSE 4200

CMD pnpm start 