version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5050:5000"
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./backend/requirements.txt:/app/requirements.txt
    environment:
      - FLASK_ENV=development
      - PORT=5000 