FROM python:3.11-slim

# Create a non-root user
RUN groupadd -r app && useradd -m -g app app

WORKDIR /app

COPY requirements.txt .

# Install requirements at build time (for speed), but also at runtime (for dev)
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

USER app

EXPOSE 5000

# Install requirements.txt every time the container starts (for dev)
CMD pip install --no-cache-dir -r requirements.txt && python app.py 