"""Initial migration

Revision ID: 407900d8ab4e
Revises: 
Create Date: 2025-06-11 16:37:38.518452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407900d8ab4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_pair', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
