name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Build Angular project
        run: pnpm run build
        working-directory: frontend

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        working-directory: frontend

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages -d dist/crypto-price-tracker/browser \
            -r https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
        working-directory: frontend